services:
  splent_feature_nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: splent/splent_feature_nginx:latest
    restart: always
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - letsencrypt:/etc/letsencrypt:ro
      - certbot_webroot:/var/www/certbot:ro
    environment:
      - NGINX_UPSTREAM_HOST=${NGINX_UPSTREAM_HOST}
      - NGINX_UPSTREAM_PORT=${NGINX_UPSTREAM_PORT}
      - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
    networks:
      - splent_network

volumes:
  letsencrypt:
  certbot_webroot:

networks:
  splent_network:
    external: true
